#!/bin/sh

# SPDX-License-Identifier: MIT

. "$(dirname "$0")/_/husky.sh"

if [ $3 -ne 1 ]; then
  exit 0
fi

function die(){
  local STATUS=$?
  echo $1 >&2
  exit $STATUS
}

if !(type gh > /dev/null 2>&1); then
  exit 0
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ "${BRANCH}" =~ ^(HEAD|main|develop)$ ]]; then
  exit 0
fi

ISSUES=$(echo "${BRANCH}" | grep -oE '#[0-9]+' | tr -d '#' | sort -nr || :)

if [[ ! ${ISSUES[@]} ]]; then
  die "💡 issue が連携されていません。"
fi

for issue in $ISSUES; do
  gh --repo uchikoshi-fes/uchikoshi-fes.jp-2022 issue view $issue || die "🚨 issue $issue を見つけられませんでした。[uchikoshi-fes/uchikoshi-fes.jp-2022]"
done
